tasks:
  build-image:
    type: build
    steps:
      - docker/build:
          image: nikhilmaripi03/demo1
          tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
          dockerfile: Dockerfile
       
